import "./globals.css";
import Navbar from "./navbar/Navbar";
import { Poppins } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });
import Footer from "./components/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <main className="pt-16">{children}</main>
        <div className="bg-slate-100 h-2" />
        <Footer />
      </body>
    </html>
  );
}
