export const cart = [
  {
    id: 1,
    Image: "./Product Images/Mutual Fund.svg",
    Title: "Mutual Fund",
    Desc: "A mutual fund is a company that pools money from many investors and invests the money in securities such as stocks, bonds, and short-term debt. The combined holdings of the mutual fund are known as its portfolio.",
    Alt: "Mutual Fund",
    Link: "/Learn/MutualFund",
  },
  {
    id: 2,
    Image: "./Product Images/Insurance.svg",
    Title: "Insurance",
    Desc: "Insurance is a way to manage your risk. When you buy insurance, you purchase protection against unexpected financial losses. The insurance company pays you or someone you choose if something bad happens to you. If you have no insurance and an accident happens, you may be responsible for all related costs.",
    Alt: "Insurance",
    Link: "/Learn/Insurance",
  },
  {
    id: 3,
    Image: "./Product Images/Fixed Deposit.svg",
    Title: "Fixed Deposit",
    Desc: "In a Fixed Deposit, you put a lump sum in your bank for a fixed tenure at an agreed rate of interest.",
    Alt: "Fixed Deposit",
    Link: "/Learn/FixedDeposite",
  },
  {
    id: 4,
    Image: "./Product Images/Stock Broking.svg",
    Title: "Stock Broking",
    Desc: "Stock Broking is a service which gives retail and institutional investors the opportunity to buy and sell equities. Stockbrokers will trade shares both on exchange and over-the-counter, dependent on where they can find the best price and liquidity.",
    Alt: "Stock Broking",
    Link: "/Learn/StockBroking",
  },
  {
    id: 5,
    Image: "./Product Images/Loans.svg",
    Title: "Loans",
    Desc: "A loan is a sum of money that one or more individuals or companies borrow from banks or other financial institutions so as to financially manage planned or unplanned events. In doing so, the borrower incurs a debt, which he has to pay back with interest and within a given period of time.",
    Alt: "Loans",
    Link: "/Learn/Loans",
  },
  {
    id: 6,
    Image: "./Product Images/PMS_AIF.svg",
    Title: "PMS/AIF",
    Desc: "Portfolio Management Services (PMS), service offered by the Portfolio Manager, is an investment portfolio in stocks, fixed income, debt, cash, structured products and other individual securities, managed by a professional money manager that can potentially be tailored to meet specific investment objectives.",
    Alt: "PMS/AIF",
    Link: "/Learn/PMSnAIF",
  },
];
